[features]
seeds = false
skip-lint = false
[programs.localnet]
exchage = "xYPFcKTfkkEytkT9WwHBvQaJdTbuqPwzq2g4aqtuEsr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lucas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
